package cloudbuildtrigger


type CloudbuildTriggerBitbucketServerTriggerConfig struct {
	// The Bitbucket server config resource that this trigger config maps to.
	//
	// Docs at Terraform Registry: {@link https://registry.terraform.io/providers/hashicorp/google/4.79.0/docs/resources/cloudbuild_trigger#bitbucket_server_config_resource CloudbuildTrigger#bitbucket_server_config_resource}
	BitbucketServerConfigResource *string `field:"required" json:"bitbucketServerConfigResource" yaml:"bitbucketServerConfigResource"`
	// Key of the project that the repo is in. For example: The key for https://mybitbucket.server/projects/TEST/repos/test-repo is "TEST".
	//
	// Docs at Terraform Registry: {@link https://registry.terraform.io/providers/hashicorp/google/4.79.0/docs/resources/cloudbuild_trigger#project_key CloudbuildTrigger#project_key}
	ProjectKey *string `field:"required" json:"projectKey" yaml:"projectKey"`
	// Slug of the repository.
	//
	// A repository slug is a URL-friendly version of a repository name, automatically generated by Bitbucket for use in the URL.
	// For example, if the repository name is 'test repo', in the URL it would become 'test-repo' as in https://mybitbucket.server/projects/TEST/repos/test-repo.
	//
	// Docs at Terraform Registry: {@link https://registry.terraform.io/providers/hashicorp/google/4.79.0/docs/resources/cloudbuild_trigger#repo_slug CloudbuildTrigger#repo_slug}
	RepoSlug *string `field:"required" json:"repoSlug" yaml:"repoSlug"`
	// pull_request block.
	//
	// Docs at Terraform Registry: {@link https://registry.terraform.io/providers/hashicorp/google/4.79.0/docs/resources/cloudbuild_trigger#pull_request CloudbuildTrigger#pull_request}
	PullRequest *CloudbuildTriggerBitbucketServerTriggerConfigPullRequest `field:"optional" json:"pullRequest" yaml:"pullRequest"`
	// push block.
	//
	// Docs at Terraform Registry: {@link https://registry.terraform.io/providers/hashicorp/google/4.79.0/docs/resources/cloudbuild_trigger#push CloudbuildTrigger#push}
	Push *CloudbuildTriggerBitbucketServerTriggerConfigPush `field:"optional" json:"push" yaml:"push"`
}

