package dataprocjob


type DataprocJobReference struct {
	// The job ID, which must be unique within the project.
	//
	// The job ID is generated by the server upon job submission or provided by the user as a means to perform retries without creating duplicate jobs
	//
	// Docs at Terraform Registry: {@link https://www.terraform.io/docs/providers/google/r/dataproc_job#job_id DataprocJob#job_id}
	JobId *string `field:"optional" json:"jobId" yaml:"jobId"`
}

